{% set name = "awacs" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudtools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: b79a379b7cce03822d6f7d76c735e7d767334a521945b5bfdc978d1c9a2537e3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - awacs
    - awacs.helpers

about:
  home: https://github.com/cloudtools/awacs
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: AWS Access Policy Language creation library
  dev_url: https://github.com/cloudtools/awacs

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - mxr-conda
